[[entries]]
id = "a584fdea-3670-4613-b52f-a1e6c1353a22"
type = "fix"
description = "Fix placement of code block when rendering `include` directive back into the Markdown file."
author = "@NiklasRosenstein"
